db_file: '/tmp/vacatures/db_file'
pages_dir: '/home/joriso/devlop/vacatures/vacature_pages'
sources_dir: '/tmp/vacatures/sources'
feeds_file : '/tmp/vacatures/sources/feeds.txt'
feeds_dir : '/tmp/vacatures/feeds'
sites_file : '/tmp/vacatures/sources/sites.txt'
sites_dir : '/tmp/vacatures/sites'
sites_data_maps : '/home/joriso/devlop/vacatures/scrapers'
json_dir : '/tmp/vacatures/json'
json_file : '/tmp/vacatures/sources/json.txt'
json_data_maps : '/home/joriso/devlop/vacatures/data_maps'
selenium_file : '/tmp/vacatures/sources/selenium.txt'
selenium_dir : '/tmp/vacatures/selenium'
data_dir  : '/tmp/vacatures/data'
public_dir : '/home/joriso/devlop/vacatures/output'
templates_dir : '/home/joriso/devlop/vacatures/templates'
www_assets: '/home/joriso/devlop/vacatures/www_assets'
